### Basic If-Else Statements:


### 1. Write a Python program to check if a given number is positive or negative.

In [2]:

x=int(input("Enter the number"))
if x>0:
    print("The given number is positive")
else:
    print("The given number is negative")

Enter the number 6


The given number is positive


### 2. Create a program that determines if a person is eligible to vote based on their age.

In [3]:
age=int(input("Enter the age of person: "))
if age>=18:
    print("person is eligible to vote")
else:
    print("Person is not eligible to vote")

Enter the age of person:  24


person is eligible to vote


### 3. Develop a program to find the maximum of two numbers using if-else statements.

In [4]:
a=int(input("Enter 1 number"))
b=int(input("Enter 2 number"))
if a>b:
    print("Number 1 is greater then number 2")
else:
    print("Number 2 is greater then number 1")

Enter 1 number 3
Enter 2 number 4


Number 2 is greater then number 1


### 4. Write a Python script to classify a given year as a leap year or not.

In [5]:
year=int(input("Enter year "))
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))
    
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))
else:
     print("{0} is not a leap year".format(year))

Enter year  2003


2003 is not a leap year


## 5. Create a program that checks whether a character is a vowel or a consonant.

In [6]:
s=str(input("Enter a character"))
if(s=='a')|(s=='e')|(s=='i')|(s=='o')|(s=='u'):
    print("Given char is vowel")
else:
     print("Given char is not a vowel")

Enter a character a


Given char is vowel


## 6. Implement a program to determine whether a given number is even or odd.

In [7]:
s=int(input("Enter a number"))
if s%2==0:
    print("Given number is even")
else:
    print("Given number is odd")

Enter a number 4


Given number is even


### 7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.

In [8]:
def my_abs(value):

    if value < 5 :
        print(value * 1)
    else:
        print(value * -1)
print(my_abs(3.5))

3.5
None


##### 8. Develop a program that determines the largest of three given numbers using if-else statements.

In [10]:
a=int(input("Enter 1 number"))
b=int(input("Enter 2 number"))
c=int(input("Enter 3 number"))
if a>b & a>c:
    print(f'{a} is greatest of all')
elif b>a & b>c:
    print(f'{b} is greatest of all')
else:
    print(f'{c} is greatest of all')


Enter 1 number 5
Enter 2 number 6
Enter 3 number 3


5 is greatest of all


### 9. Create a program that checks if a given string is a palindrome.

In [11]:
a=str(input("Enter the string"))
b=a[::-1]
if a==b:
    print("Given string is palindrome")
else:
     print("Given string is not palindrome")

Enter the string aba


Given string is palindrome


#### 10. Write a Python program to calculate the grade based on a student's score.

In [12]:
a=int(input("Enter the grade"))
if a>=95:
    print("A++")
elif a>=90:
    print("A")
elif a>=80:
    print("B")
elif a>=70:
    print("C")
else:
    print("D")


Enter the grade 94


A


### 11. Write a program to find the largest among three numbers using nested if-else statements.

In [13]:

n1=int(input("Enter 1 number"))
n2=int(input("Enter 2 number"))
n3=int(input("Enter 3 number"))


if (n1 >= n2): 
    if (n1 >= n3):
        print(f"{n1} is the largest number.");
    else:
        print(f"{n3}is the largest number.");


else:
    if (n2 >= n3):
        print(f"{n2} is the largest number.");
    else:
        print(f"{n3} is the largest number.");


Enter 1 number 3
Enter 2 number 4
Enter 3 number 5


5 is the largest number.


### 12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.

In [14]:
a=int(input("Enter 1 side of triangle"))
b=int(input("Enter 2 side of triangle"))
c=int(input("Enter 3 side of triangle"))
if (a == b & a == c):
    print("equilateral")
elif (a == b | a == c):
    print("isosceles")
else:
    print("scalene")
  

Enter 1 side of triangle 3
Enter 2 side of triangle 3
Enter 3 side of triangle 3


equilateral


### 13. Develop a program that checks if a year is a leap year and also if it is a century year.

In [15]:
x=int(input("Enter the year"))
if x%4==0 & x%400==0 & x%100==0:
    print("Given year is a leap year and century year")
elif  x%4==0 & x%400==0:
    print("Given year is a leap year")
elif x%100==0:
    print("Given Year is a century year")
else:
    print("Given year is not a leap or century year")

Enter the year 2004


Given year is a leap year and century year


## 14. Write a Python script to determine if a number is positive, negative, or zero.

In [16]:
number = float(input("Enter a number: "))

# Check for Positive Number
if number > 0:
   print("Number Entered is a Positive number")

#Check for Negative Number
elif number < 0:
   print("Number Entered is a Negative number")

# if Number is not Positive and not Negative then it is 0
else:
   print("Number Entered is Zero")

Enter a number:  4


Number Entered is a Positive number


### 15. Create a program to check if a person is a teenager (between 13 and 19 years old).

In [17]:
x=int(input("Enter the age"))
if(x>=13 & x<=19):
    print("It's in the range")
else:
    print("It's not in the range")

Enter the age 54


It's in the range


## 16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).

In [18]:
angle=int(input("Enter the angle"))
if angle >=90:
    if angle==90:
        print( "right angle")
    else:
        print("obtuse")
else:
     print( "acute")

Enter the angle 45


acute


## 17. Write a Python program to calculate the roots of a quadratic equation.

## 18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2 for Tuesday, etc.).

In [19]:
day = int(input("Enter a number from 1 to 7: "))

if day == 1:
    print(day, "is Sunday")
elif day == 2:
    print(day, "is Monday")
elif day == 3:
    print(day, "is Tuesday")
elif day == 4:
    print(day, "is Wednesday")
elif day == 5:
    print(day, "is Thursday")
elif day == 6:
    print(day, "is Friday")
elif day == 7:
    print(day, "is Saturday")
else:
    print("Wrong input! Please enter a number from 1 to 7.")

Enter a number from 1 to 7:  5


5 is Thursday


## 19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400.

In [20]:
year = int(input("Enter a year(yyyy): "))

if year % 4 == 0:
    if year % 100 != 0:
        print(year, "is a leap year.")
    elif year % 400 == 0:
        print(year, "is a leap year.")
    else:
        print(year, "is not a leap year.")
else:
    print(year, "is not a leap year.")


Enter a year(yyyy):  2014


2014 is not a leap year.


## 20. Develop a program that checks if a given number is prime or not using nested if-else statements.

In [22]:
if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)

### 21. Write a Python program to assign grades based on different ranges of scores using elif statements.

In [23]:
a=int(input("Enter the grade"))
if a>=95:
    print("A++")
elif a>=90:
    print("A")
elif a>=80:
    print("B")
elif a>=70:
    print("C")
else:
    print("D")


Enter the grade 44


D


### 22. Implement a program to determine the type of a triangle based on its angles.

In [24]:
angle=int(input("Enter the degree of angle"))
if angle>90:
    print("Obtuse angle")
elif angle==90:
    print("Right angle triangle")
else:
    print("Actue angle triangle")

Enter the degree of angle 5


Actue angle triangle


### 23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using elif statements.

In [25]:
bmi = float(input("Enter your weight in kg: "))
height = float(input("Enter your height in meters: "))
if bmi < 18.5:
    print("Underweight")
elif bmi < 25:
    print("Normal")
elif bmi < 30:
    print("Overweight")
else:
    print("Obese")

Enter your weight in kg:  5
Enter your height in meters:  4


Underweight


### 24. Create a program that determines whether a given number is positive, negative, or zero using elif statements.

In [26]:
x=int(input("Enter a number"))
if x>0:
    print("Positive")
elif x==0:
    print("zero")
else:
    print("negative")

Enter a number 4


Positive


### 25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif statements.

In [27]:
x=str(input("Enter the alphabate"))
if x.isupper():
    print("Uppercase")
elif x.islower():
    print("lowecase")
else:
    print("Special")

Enter the alphabate q


lowecase


### 26. Implement a program to calculate the discounted price based on different purchase amounts using elif  statements.

In [28]:
p=int(input('Enter purchase amount '))

if p<=5000:
    dis=0
elif p>5000 and p<=10000:
    dis=(p-5000)*(10/100.0)
elif p>10000 and p<=20000:
    dis=(p-10000)*(20/100.0)
elif p>20000 and p<=30000:
    dis=(p-20000)*(30/100.0)
else:
    dis=(p-30000)*(40/100.0)

print('Discount Amount = {:.2f}'.format(dis))
print('Net Bill Amount = {:.2f}'.format(p-dis))

Enter purchase amount  70000


Discount Amount = 16000.00
Net Bill Amount = 54000.00


### 27. Develop a program to calculate the electricity bill based on different consumption slabs using elif statements.

In [29]:
unit = int(input("Enter your unit: "))
if unit <= 100:
    bill = unit * 3.46
elif unit >= 101 and unit <= 300:
    bill = 346 + ((unit - 100) * 7.43)
elif unit >= 301 and unit <= 500:
    bill = 346 + 1486 + ((unit - 300) * 10.32)
else:
    bill = 346 + 1486 + 2064 + ((unit - 500) * 11.71)
print("Bill Per Unit:",bill)
bill = bill + (unit*1.45)
print("Bill after adding Line rent:",bill)
bill = bill + 100
print("Bill after adding Meter rent:",bill)
bill = bill + (bill*0.16)
print("Total Bill after adding tax:",bill)

Enter your unit:  4


Bill Per Unit: 13.84
Bill after adding Line rent: 19.64
Bill after adding Meter rent: 119.64
Total Bill after adding tax: 138.7824


### 28. Create a program to determine the type of quadrilateral based on its angles and sides using elif statements.

In [30]:
print("Input lengths of the triangle sides: ")
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))

if x == y == z:
	print("Equilateral triangle")
elif x==y or y==z or z==x:
	print("isosceles triangle")
else:
	print("Scalene triangle")


Input lengths of the triangle sides: 


x:  4
y:  5
z:  4


isosceles triangle


### 29. Write a Python script to determine the season based on a user-provided month using elif statements.

In [31]:
month = input("Input the month (e.g. January, February etc.): ")

if month in ('January', 'February', 'March'):
	print('winter')
elif month in ('April', 'May', 'June'):
	prrint('spring')
elif month in ('July', 'August', 'September'):
	print('summer')
else:
	print('autumn')
    

Input the month (e.g. January, February etc.):  November


autumn


### 30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using elif statements.

In [32]:
year = int(input("Enter a year: "))
month = int(input("Enter a month: "))
if year % 4 == 0 and year % 100 != 0:
    print("It's a leap year!")
elif year % 4 != 0 and year % 100 == 0:
    print("It's a common year!")
elif month == 3:
    print("It's March, which has 31 days!")
else:
    print("It's not a leap year or March!")


Enter a year:  2004
Enter a month:  12


It's a leap year!


# Basic Level:

1. Write a Python program that checks if a given number is positive, negative, or zero.

In [33]:
x=int(input("Enter number"))
if x>0:
    print("positive")
elif x==0:
    print("Zero")
else:
    print("Negative")

Enter number 4


positive


3. Write a program to find the maximum of two given numbers using conditional statements.

In [34]:
x=int(input("Enter 1 number"))
y=int(input("Enter 2 number"))
if x>y:
    print("number 1 is grater then number 2")
else:
     print("number 2 is grater then number 1")


Enter 1 number 4
Enter 2 number 5


number 2 is grater then number 1


4. Develop a program that calculates the grade of a student based on their exam score.

In [35]:
a=int(input("Enter the grade"))
if a>=95:
    print("A++")
elif a>=90:
    print("A")
elif a>=80:
    print("B")
elif a>=70:
    print("C")
else:
    print("D")


Enter the grade 99


A++


5. Create a program that checks if a year is a leap year or not.

In [36]:
year = int(input("Enter a year(yyyy): "))

if year % 4 == 0:
    if year % 100 != 0:
        print(year, "is a leap year.")
    elif year % 400 == 0:
        print(year, "is a leap year.")
    else:
        print(year, "is not a leap year.")
else:
    print(year, "is not a leap year.")


Enter a year(yyyy):  2002


2002 is not a leap year.


13. Develop a program that calculates the factorial of a given number using recursion.

In [1]:
def fact_rec(n):
	if n < 0:
		return
	elif n <= 1:
		return 1
	else:
		return n*fact_rec(n-1)

print(fact_rec(4))

24


Write a program that calculates the average of a list of numbers, excluding the smallest and largest values.


In [15]:
numbers=[1,2,3,4,5,6,7,8]
x = sum(numbers)
    
smallest = min(numbers)
largest = max(numbers)
x=x-smallest-largest
avg=x/(len(numbers)-2)
print(avg)

4.5


18. Develop a program that converts a given temperature from Celsius to Fahrenheit.

In [16]:
celsius = 37.5

# calculate fahrenheit
fahrenheit = (celsius * 1.8) + 32
print('%0.1f degree Celsius is equal to %0.1f degree Fahrenheit' %(celsius,fahrenheit))

37.5 degree Celsius is equal to 99.5 degree Fahrenheit


20. Write a program that determines the roots of a cubic equation using the Cardano formula.


In [17]:
def solve(a,b,c,d):
    Q = (3*a*c - (b**2)) / (9*(a**2))
    R = (9*a*b*c - 27*(a**2)*d - 2*(b**3)) / (54*(a**3))
    D = (Q**3) + (R**2)
    S = (R + (D**(1/2)))**(1/3)
    T = (R - (D**(1/2)))**(1/3)

    x1 = S + T - (b/(3*a))
    x2 = -((S + T)/2) - (b/(3*a)) + 0.5j * (3**(1/2)) * (S - T)
    x3 = -((S + T)/2) - (b/(3*a)) - 0.5j * (3**(1/2)) * (S - T)

print(x1,x2,x3)

### 21. Create a program that calculates the income tax based on the user's income and tax brackets.

In [18]:
def calculate(amount, percent):
	return (amount * percent) / 100

def calculate_income_tax(total_income:
						float) -> float:

	if total_income <= 250000:
		return 0
	elif total_income <= 500000:
		return calculate(total_income -
						250000, 5)
	elif total_income <= 750000:
		return calculate(total_income -
						500000, 10) + 12500
	elif total_income <= 1000000:
		return calculate(total_income -
						750000, 15) + 37500
	elif total_income <= 1250000:
		return calculate(total_income -
						1000000, 20) + 75000
	elif total_income <= 1500000:
		return calculate(total_income -
						1250000, 25) + 125000
	else:
		return calculate(total_income -
						1500000, 30) + 187500


if __name__ == '__main__':
	total_income = float(input("What's your \
					annual income?\n>>> "))
	tax = calculate_income_tax(total_income)
	print(f"Total tax applicable at \
					₹{total_income} is ₹{tax}")

    

What's your 					annual income?
>>>  2000000


Total tax applicable at 					₹2000000.0 is ₹337500.0


### 22. Write a program that simulates a rock-paper-scissors game against the computer.

In [20]:
import random

options = ("rock", "paper", "scissors")
running = True

while running:

    player = None
    computer = random.choice(options)

    while player not in options:
        player = input("Enter a choice (rock, paper, scissors): ")

    print(f"Player: {player}")
    print(f"Computer: {computer}")

    if player == computer:
        print("It's a tie!")
    elif player == "rock" and computer == "scissors":
        print("You win!")
    elif player == "paper" and computer == "rock":
        print("You win!")
    elif player == "scissors" and computer == "paper":
        print("You win!")
    else:
        print("You lose!")

    if not input("Play again? (y/n): ").lower() == "y":
        running = False

print("Thanks for playing!")

Enter a choice (rock, paper, scissors):  paper


Player: paper
Computer: rock
You win!


Play again? (y/n):  n


Thanks for playing!


## 23. Develop a program that generates a random password based on user preferences (length, complexity).

In [26]:
import string
length=12
complexity=3
password = ''
for i in range(length):
    password += random.choice(string.ascii_letters + string.digits)

print(password)

x9qtgvAAfmGN


## 25. Build a program that solves a linear equation for x, considering different cases.

In [27]:
print("Input the value of a, b, c, d, e, f:")
a, b, c, d, e, f = map(float, input().split())
n = a*e - b*d
print("Values of x and y:")
if n != 0:
    x = (c*e - b*f) / n
    y = (a*f - c*d) / n
    print('{:.3f} {:.3f}'.format(x+0, y+0))

Input the value of a, b, c, d, e, f:


 5 8 6 7 9 4


Values of x and y:
-2.000 2.000


32. Develop a program that performs matrix addition and subtraction based on user input.

In [28]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
 
# creating second matrix
B = np.array([[4, 5], [6, 7]])
 
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
 
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

print("Substraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]
Substraction of two matrix
[[-3 -3]
 [-3 -3]]


33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean algorithm.

In [29]:
def gcd(a,b):
    while(b != 0):
        a, b = b, a % b
    return abs(a)
print(gcd(10, 5))  
print(gcd(48, 36))

5
12


## 34. Build a program that performs matrix multiplication using nested loops and conditional statements.